//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobile_ca.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mobile_ca.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;use strict&quot;;
        ///
        ///var config = null;
        ///
        ///function getIdFromPubkey(pubkey) {
        ///    var id = null;
        ///    $(&quot;#keys tbody [data-content]&quot;).each(function () {
        ///        var key = $(this).data(&quot;content&quot;);
        ///        if (key.pubkey === pubkey) {
        ///            id = key.id;
        ///        }
        ///    });
        ///    return id;
        ///}
        ///
        ///function getCertsForPubkey(pubkey) {
        ///    var certList = { ca: [], cert: [] };
        ///    $(&quot;#ca tbody [data-content]&quot;).each(function (v) {
        ///        var cert = $(this).data(&quot;content&quot;);
        ///        if (cert.pubkey === pubk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string api_js {
            get {
                return ResourceManager.GetString("api_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_css {
            get {
                return ResourceManager.GetString("bootstrap_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///  * Bootstrap v4.0.0 (https://getbootstrap.com)
        ///  * Copyright 2011-2018 The Bootstrap Authors (https://github.com/twbs/bootstrap/graphs/contributors)
        ///  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        ///  */
        ///!function(t,e){&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module?e(exports,require(&quot;jquery&quot;),require(&quot;popper.js&quot;)):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;exports&quot;,&quot;jquery&quot;,&quot;popper.js&quot;],e):e(t.bootstrap={},t.jQuery,t.Popper)}(this,function(t,e,n){&quot;use strict&quot;;func [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_js {
            get {
                return ResourceManager.GetString("bootstrap_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///}.
        /// </summary>
        internal static string custom_css {
            get {
                return ResourceManager.GetString("custom_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;bootstrap.css&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;jquery.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;popper.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;bootstrap.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;api [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.2.1 -ajax,-ajax/jsonp,-ajax/load,-ajax/parseXML,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-event/ajax,-effects,-effects/Tween,-effects/animatedSelector | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(a,b){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_slim_js {
            get {
                return ResourceManager.GetString("jquery_slim_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// Copyright (C) Federico Zivolo 2017
        /// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).
        /// */(function(e,t){&apos;object&apos;==typeof exports&amp;&amp;&apos;undefined&apos;!=typeof module?module.exports=t():&apos;function&apos;==typeof define&amp;&amp;define.amd?define(t):e.Popper=t()})(this,function(){&apos;use strict&apos;;function e(e){return e&amp;&amp;&apos;[object Function]&apos;==={}.toString.call(e)}function t(e,t){if(1!==e.nodeType)return[];var o=getComputedStyle(e,null);return t?o[t]:o}function o(e){return&apos;HTML&apos;===e.nodeName?e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string popper_js {
            get {
                return ResourceManager.GetString("popper_js", resourceCulture);
            }
        }
    }
}
